import { StyleSheet } from 'react-native';
import Constants from 'expo-constants';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        paddingHorizontal:24,
        paddingTop: 10 + Constants.statusBarHeight,
      },
      containerBack:{
        justifyContent:'space-between',
        flexDirection:'row',
        alignItems:'center',
        padding:24,
        paddingTop:44,
       },
      containerbox:{
        flexDirection:'row',
        justifyContent:'center',
        marginBottom:30,
        marginTop:30
      },
      containerboxText:{
       fontSize:23,
       color:'#FFD246',
       fontWeight:'700',
       paddingHorizontal:10,
      },
      main:{
        flexDirection:'row',
        justifyContent:'center'
      },
      mainGrid:{},
      mainlogo:{
        width:227,
        height:118,
        marginBottom:90,
      },
      mainInput1:{
        backgroundColor:'#fff',
        width:246,
        height:40,
        marginBottom:8,
        borderRadius:14,
        fontSize:16,
        paddingHorizontal:20,
      },
      mainInput2:{
        backgroundColor:'#fff',
        width:188,
        height:40,
        marginBottom:8,
        borderRadius:14,
        fontSize:16,
        paddingHorizontal:20,
      },
      mainInput3:{
        backgroundColor:'#fff',
        width:239,
        height:40,
        marginBottom:8,
        borderRadius:14,
        fontSize:16,
        paddingHorizontal:20,
      },
      mainInput4:{
        backgroundColor:'#fff',
        width:260,
        height:40,
        marginBottom:8,
        borderRadius:14,
        fontSize:16,
        paddingHorizontal:20,
      },
      mainInput5:{
        backgroundColor:'#fff',
        width:242,
        height:40,
        marginBottom:8,
        borderRadius:14,
        fontSize:16,
        paddingHorizontal:20,
      },
      mainInput6:{
        backgroundColor:'#fff',
        width:73,
        height:40,
        marginBottom:8,
        borderRadius:14,
        fontSize:16,
        paddingHorizontal:20,
      },
      mainInput:{
        backgroundColor:'#fff',
        width:127,
        height:40,
        marginBottom:8,
        borderRadius:14,
        fontSize:16,
        paddingHorizontal:20,
      },
      mainInputText:{
        color:'#fff',
        fontSize:18,
        fontWeight:'800',
        marginTop:10,
        paddingHorizontal:10
      },
      mainInputTextEsqueceu:{
       flexDirection:'row',
       justifyContent:'space-between',
       marginLeft:200,
       marginBottom:20,
       
      },
      mainInputTextEsqueceuText:{color:'#fff',},

      mainInputButton:{
        backgroundColor:'#fff',
        width:219,
        height:50,
        borderRadius:14,
        justifyContent:'center',
        alignItems:'center',
        textAlign:'center'
      },
      mainInputButtonText:{
        fontSize:16,
        color:'#535353'
      },
      footer:{
        justifyContent:'center',
        alignItems:'center',
        height:130,
        top:50
      },
      footerImg:{
        width:133,
        height:70,
      },
      footerTextBold:{
        fontWeight:'800',
        color:'#fff',
        fontSize:14,
      },
      mainpastas:{
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
        marginTop:10,
        paddingHorizontal:10,
      },
      mainpastasText:{
        color:'#FFD246',
        fontSize:16,
        fontWeight:'800',
        marginTop:10
      },
      containerButton:{
        width:120,
        marginTop:20,
        height:50,
        borderRadius:10,
        marginLeft:110,
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:'#FFD246'
      },
      containerButtonText:{
        color:'#000',
        fontWeight:'500',
        fontSize:20,
      },
})

export default styles;