import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,  
      },
      containerBack:{
       justifyContent:'space-between',
       flexDirection:'row',
       alignItems:'center',
       padding:24,
       paddingTop:60,
      },
      containerbox:{
        flexDirection:'row',
        justifyContent:'center',
        marginBottom:30,
        marginTop:120
      },
      containerboxText:{
       fontSize:23,
       color:'#FFD246',
       fontWeight:'700',
       paddingHorizontal:10,
      },
      main:{
        flexDirection:'row',
        justifyContent:'center'
      },
      mainGrid:{},
      mainlogo:{
        width:227,
        height:118,
        marginBottom:90,
      },
      mainInput1:{
        backgroundColor:'#fff',
        width:274,
        height:40,
        marginBottom:8,
        borderRadius:14,
        fontSize:16,
        paddingHorizontal:20,
      },
      mainInput2:{
        backgroundColor:'#fff',
        width:144,
        height:40,
        marginBottom:8,
        borderRadius:14,
        fontSize:16,
        paddingHorizontal:20,
      },
      mainInput3:{
        backgroundColor:'#fff',
        width:238,
        height:40,
        marginBottom:8,
        borderRadius:14,
        fontSize:16,
        paddingHorizontal:20,
      },
      mainInput4:{
        backgroundColor:'#fff',
        width:145,
        height:40,
        marginBottom:8,
        borderRadius:14,
        fontSize:16,
        paddingHorizontal:20,
      },
      mainInput5:{
        backgroundColor:'#fff',
        width:270,
        height:40,
        marginBottom:8,
        borderRadius:14,
        fontSize:16,
        paddingHorizontal:20,
      },
      mainInput:{
        backgroundColor:'#fff',
        width:195,
        height:40,
        marginBottom:8,
        borderRadius:14,
        fontSize:16,
        paddingHorizontal:20,
      },
      mainInputText:{
        color:'#fff',
        fontSize:18,
        fontWeight:'800',
        marginTop:10,
        paddingHorizontal:10
      },

      mainInputButton:{
        backgroundColor:'#fff',
        width:129,
        height:50,
        borderRadius:14,
        justifyContent:'center',
        alignItems:'center',
        textAlign:'center'
      },
      mainInputButtonText:{
        fontSize:16,
        color:'#535353'
      },
      footer:{
        justifyContent:'center',
        alignItems:'center',
        height:130,
        top:30
      },
      footerImg:{
        width:133,
        height:70
      },
      footerTextBold:{
        fontWeight:'800',
        color:'#fff',
        fontSize:14,
      },
      mainpastas:{
       alignItems:'center',
       justifyContent:'center',
       top:30
      },
})

export default styles;